<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="MyProjectDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.logindetail" Member="logindetails">
    <Type Name="logindetail">
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="s_ques" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="s_ans" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="u_type" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ImageDetail" Member="ImageDetails">
    <Type Name="ImageDetail">
      <Column Name="Imageid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Imagename" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ImagePath" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Msgdetail" Member="Msgdetails">
    <Type Name="Msgdetail">
      <Column Name="msgid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sender1" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="rece" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="subject" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="attachment" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="date1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Time1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="draft" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.HostingLogin" Member="HostingLogins">
    <Type Name="HostingLogin">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DomainName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ServerName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HostLoginStatus" Member="HostLoginStatus">
    <Type Name="HostLoginStatus">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LastLoginIP" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="StartTime" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EndTime" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TimeDuration" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Memberships" Member="Memberships">
    <Type Name="Membership">
      <Column Name="UserId" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFailedAttempt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Role" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="isSuperAdmin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isRejected" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Membership_Registration" Member="Registrations" ThisKey="UserId" OtherKey="GuidId" Type="Registration" />
    </Type>
  </Table>
  <Table Name="dbo.Registration" Member="Registrations">
    <Type Name="Registration">
      <Column Name="UserId" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GuidId" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="a_ques" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="s_ans" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dob" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="mobile" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="country" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DateTime" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Membership_Registration" Member="Membership" ThisKey="GuidId" OtherKey="UserId" Type="Membership" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Applications" Member="aspnet_Applications">
    <Type Name="aspnet_Application">
      <Column Name="ApplicationName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredApplicationName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="aspnet_Application_aspnet_Membership" Member="aspnet_Memberships" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Membership" />
      <Association Name="aspnet_Application_aspnet_Path" Member="aspnet_Paths" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Path" />
      <Association Name="aspnet_Application_aspnet_Role" Member="aspnet_Roles" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Role" />
      <Association Name="aspnet_Application_aspnet_User" Member="aspnet_Users" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_User" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Membership" Member="aspnet_Memberships">
    <Type Name="aspnet_Membership">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MobilePIN" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LoweredEmail" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="aspnet_Membership_BodyContent" Member="BodyContents" ThisKey="UserId" OtherKey="UserId" Type="BodyContent" />
      <Association Name="aspnet_Membership_AdminProfile" Member="AdminProfiles" ThisKey="UserId" OtherKey="UserId" Type="AdminProfile" />
      <Association Name="aspnet_Membership_SiteUser" Member="SiteUsers" ThisKey="UserId" OtherKey="CreatorId" Type="SiteUser" />
      <Association Name="aspnet_Membership_ActivateUser" Member="ActivateUsers" ThisKey="UserId" OtherKey="UserId" Type="ActivateUser" />
      <Association Name="aspnet_Membership_Website" Member="Websites" ThisKey="UserId" OtherKey="UserId" Type="Website" />
      <Association Name="aspnet_Membership_DatabaseDetail" Member="DatabaseDetails" ThisKey="UserId" OtherKey="UserId" Type="DatabaseDetail" />
      <Association Name="aspnet_Membership_TableDetail" Member="TableDetails" ThisKey="UserId" OtherKey="UserId" Type="TableDetail" />
      <Association Name="aspnet_Membership_TableColumnDetail" Member="TableColumnDetails" ThisKey="UserId" OtherKey="UserId" Type="TableColumnDetail" />
      <Association Name="aspnet_Application_aspnet_Membership" Member="aspnet_Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
      <Association Name="aspnet_User_aspnet_Membership" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Paths" Member="aspnet_Paths">
    <Type Name="aspnet_Path">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="PathId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredPath" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Path_aspnet_PersonalizationAllUser" Member="aspnet_PersonalizationAllUser" ThisKey="PathId" OtherKey="PathId" Type="aspnet_PersonalizationAllUser" Cardinality="One" />
      <Association Name="aspnet_Path_aspnet_PersonalizationPerUser" Member="aspnet_PersonalizationPerUsers" ThisKey="PathId" OtherKey="PathId" Type="aspnet_PersonalizationPerUser" />
      <Association Name="aspnet_Application_aspnet_Path" Member="aspnet_Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_PersonalizationAllUsers" Member="aspnet_PersonalizationAllUsers">
    <Type Name="aspnet_PersonalizationAllUser">
      <Column Name="PathId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PageSettings" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Path_aspnet_PersonalizationAllUser" Member="aspnet_Path" ThisKey="PathId" OtherKey="PathId" Type="aspnet_Path" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_PersonalizationPerUser" Member="aspnet_PersonalizationPerUsers">
    <Type Name="aspnet_PersonalizationPerUser">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PathId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="PageSettings" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Path_aspnet_PersonalizationPerUser" Member="aspnet_Path" ThisKey="PathId" OtherKey="PathId" Type="aspnet_Path" IsForeignKey="true" />
      <Association Name="aspnet_User_aspnet_PersonalizationPerUser" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Profile" Member="aspnet_Profiles">
    <Type Name="aspnet_Profile">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PropertyNames" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PropertyValuesString" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PropertyValuesBinary" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_aspnet_Profile" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Roles" Member="aspnet_Roles">
    <Type Name="aspnet_Role">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredRoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="aspnet_Role_aspnet_UsersInRole" Member="aspnet_UsersInRoles" ThisKey="RoleId" OtherKey="RoleId" Type="aspnet_UsersInRole" />
      <Association Name="aspnet_Application_aspnet_Role" Member="aspnet_Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_SchemaVersions" Member="aspnet_SchemaVersions">
    <Type Name="aspnet_SchemaVersion">
      <Column Name="Feature" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompatibleSchemaVersion" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsCurrentVersion" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Users" Member="aspnet_Users">
    <Type Name="aspnet_User">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_aspnet_Membership" Member="aspnet_Membership" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Membership" Cardinality="One" />
      <Association Name="aspnet_User_aspnet_PersonalizationPerUser" Member="aspnet_PersonalizationPerUsers" ThisKey="UserId" OtherKey="UserId" Type="aspnet_PersonalizationPerUser" />
      <Association Name="aspnet_User_aspnet_Profile" Member="aspnet_Profile" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Profile" Cardinality="One" />
      <Association Name="aspnet_User_aspnet_UsersInRole" Member="aspnet_UsersInRoles" ThisKey="UserId" OtherKey="UserId" Type="aspnet_UsersInRole" />
      <Association Name="aspnet_Application_aspnet_User" Member="aspnet_Application" ThisKey="ApplicationId" OtherKey="ApplicationId" Type="aspnet_Application" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_UsersInRoles" Member="aspnet_UsersInRoles">
    <Type Name="aspnet_UsersInRole">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="aspnet_Role_aspnet_UsersInRole" Member="aspnet_Role" ThisKey="RoleId" OtherKey="RoleId" Type="aspnet_Role" IsForeignKey="true" />
      <Association Name="aspnet_User_aspnet_UsersInRole" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_WebEvent_Events" Member="aspnet_WebEvent_Events">
    <Type Name="aspnet_WebEvent_Event">
      <Column Name="EventId" Type="System.String" DbType="Char(32) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EventTimeUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EventType" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="EventSequence" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="EventOccurrence" Type="System.Decimal" DbType="Decimal(19,0) NOT NULL" CanBeNull="false" />
      <Column Name="EventCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventDetailCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="ApplicationPath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="ApplicationVirtualPath" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="MachineName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="RequestUrl" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="ExceptionType" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Details" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.BodyContents" Member="BodyContents">
    <Type Name="BodyContent">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="WebsiteName" Type="System.String" DbType="VarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="BodyContent_Page" Member="Pages" ThisKey="WebsiteName" OtherKey="WebsiteName" Type="Page" />
      <Association Name="BodyContent_SubPage" Member="SubPages" ThisKey="WebsiteName" OtherKey="WebsiteName" Type="SubPage" />
      <Association Name="aspnet_Membership_BodyContent" Member="aspnet_Membership" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Membership" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pages" Member="Pages">
    <Type Name="Page">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PageName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PageContents" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="WebsiteName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="BodyContent_Page" Member="BodyContent" ThisKey="WebsiteName" OtherKey="WebsiteName" Type="BodyContent" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubPages" Member="SubPages">
    <Type Name="SubPage">
      <Column Name="userid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="WebsiteName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="PageName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="BodyContent_SubPage" Member="BodyContent" ThisKey="WebsiteName" OtherKey="WebsiteName" Type="BodyContent" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdminProfile" Member="AdminProfiles">
    <Type Name="AdminProfile">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserImgPath" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Rejected" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="aspnet_Membership_AdminProfile" Member="aspnet_Membership" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Membership" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SiteUsers" Member="SiteUsers">
    <Type Name="SiteUser">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatorId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IsRejected" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="aspnet_Membership_SiteUser" Member="aspnet_Membership" ThisKey="CreatorId" OtherKey="UserId" Type="aspnet_Membership" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActivateUser" Member="ActivateUsers">
    <Type Name="ActivateUser">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ActivationKey" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IsActivated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsExpired" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="aspnet_Membership_ActivateUser" Member="aspnet_Membership" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Membership" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Websites" Member="Websites">
    <Type Name="Website">
      <Column Name="WebsiteId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="WebsiteName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Website_WebsitePage" Member="WebsitePages" ThisKey="WebsiteId" OtherKey="WebsiteId" Type="WebsitePage" />
      <Association Name="Website_DatabaseDetail" Member="DatabaseDetails" ThisKey="WebsiteId" OtherKey="DbForWebsiteId" Type="DatabaseDetail" />
      <Association Name="aspnet_Membership_Website" Member="aspnet_Membership" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Membership" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.WebsitePages" Member="WebsitePages">
    <Type Name="WebsitePage">
      <Column Name="PageId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WebsiteId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PageName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Website_WebsitePage" Member="Website" ThisKey="WebsiteId" OtherKey="WebsiteId" Type="Website" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DatabaseDetails" Member="DatabaseDetails">
    <Type Name="DatabaseDetail">
      <Column Name="DatabaseId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DatabaseName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="DbForWebsiteId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WebsiteName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DatabaseDetail_TableDetail" Member="TableDetails" ThisKey="DatabaseId" OtherKey="DatabaseId" Type="TableDetail" />
      <Association Name="aspnet_Membership_DatabaseDetail" Member="aspnet_Membership" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Membership" IsForeignKey="true" />
      <Association Name="Website_DatabaseDetail" Member="Website" ThisKey="DbForWebsiteId" OtherKey="WebsiteId" Type="Website" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TableDetails" Member="TableDetails">
    <Type Name="TableDetail">
      <Column Name="TableId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TableName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DatabaseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WebsiteName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="TableDetail_TableColumnDetail" Member="TableColumnDetails" ThisKey="TableId" OtherKey="TableId" Type="TableColumnDetail" />
      <Association Name="aspnet_Membership_TableDetail" Member="aspnet_Membership" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Membership" IsForeignKey="true" />
      <Association Name="DatabaseDetail_TableDetail" Member="DatabaseDetail" ThisKey="DatabaseId" OtherKey="DatabaseId" Type="DatabaseDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TableColumnDetails" Member="TableColumnDetails">
    <Type Name="TableColumnDetail">
      <Column Name="ColumnId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TableId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TableName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ColumnName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ColumnDataType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="aspnet_Membership_TableColumnDetail" Member="aspnet_Membership" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Membership" IsForeignKey="true" />
      <Association Name="TableDetail_TableColumnDetail" Member="TableDetail" ThisKey="TableId" OtherKey="TableId" Type="TableDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.proc_retrieve_second_row" Method="proc_retrieve_second_row">
    <ElementType Name="proc_retrieve_second_rowResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LastLoginIP" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="StartTime" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EndTime" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TimeDuration" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Date" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>